[package]
name = "rustychain"
version = "0.1.0"
authors = ["Daniel Westheide <daniel.westheide@innoq.com>"]

[dependencies]
crypto-hash = "0.3.1"
serde = "1.0.39"
serde_derive = "1.0.39"
serde_json = "1.0.15"
reqwest = "0.8.5"
rouille = "2.1.0"
uuid = { version = "0.6.3", features = ["v4"] }
